# Generated by Django 5.2.10 on 2026-01-06 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivoAdjunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('tipo_mime', models.CharField(blank=True, max_length=100, null=True)),
                ('ruta_almacenamiento', models.CharField(blank=True, max_length=500, null=True)),
                ('tamano_bytes', models.BigIntegerField(blank=True, null=True)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Archivo Adjunto',
                'verbose_name_plural': 'Archivos Adjuntos',
                'db_table': 'archivos_adjuntos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol_asignacion', models.CharField(choices=[('Responsable', 'Responsable'), ('Colaborador', 'Colaborador'), ('Supervisor', 'Supervisor')], default='Responsable', max_length=20)),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Asignación',
                'verbose_name_plural': 'Asignaciones',
                'db_table': 'asignaciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entidad', models.CharField(max_length=50)),
                ('accion', models.CharField(choices=[('INSERT', 'INSERT'), ('UPDATE', 'UPDATE'), ('DELETE', 'DELETE'), ('LOGIN', 'LOGIN'), ('LOGOUT', 'LOGOUT')], max_length=10)),
                ('entidad_id', models.BigIntegerField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Auditoría',
                'verbose_name_plural': 'Auditorías',
                'db_table': 'auditoria',
                'ordering': ['-fecha'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'db_table': 'categorias',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DataCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(blank=True, max_length=150, null=True)),
                ('tipo', models.CharField(choices=[('Principal', 'Principal'), ('Backup', 'Backup'), ('Secundario', 'Secundario')], default='Principal', max_length=20)),
            ],
            options={
                'verbose_name': 'Data Center',
                'verbose_name_plural': 'Data Centers',
                'db_table': 'data_centers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Elemento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('HOST', 'HOST'), ('CLF', 'CLF'), ('ENM', 'ENM'), ('SWITCH', 'SWITCH'), ('DCGW', 'DCGW'), ('EAS', 'EAS'), ('OPC', 'OPC'), ('OTRO', 'OTRO')], default='OTRO', max_length=10)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Elemento',
                'verbose_name_plural': 'Elementos',
                'db_table': 'elementos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
                'db_table': 'estados',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadoHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('comentario', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Estado Histórico',
                'verbose_name_plural': 'Estados Históricos',
                'db_table': 'estados_historicos',
                'ordering': ['-fecha_cambio'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Observacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField()),
                ('tipo', models.CharField(choices=[('General', 'General'), ('Técnica', 'Técnica'), ('Seguimiento', 'Seguimiento'), ('Escalamiento', 'Escalamiento')], default='General', max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Observación',
                'verbose_name_plural': 'Observaciones',
                'db_table': 'observaciones',
                'ordering': ['-fecha'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('contacto', models.CharField(blank=True, max_length=150, null=True)),
                ('correo_contacto', models.CharField(blank=True, max_length=150, null=True)),
                ('telefono_contacto', models.CharField(blank=True, max_length=50, null=True)),
                ('pais', models.CharField(blank=True, max_length=100, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'db_table': 'proveedores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RelacionTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_relacion', models.CharField(choices=[('Depende de', 'Depende de'), ('Relacionado con', 'Relacionado con'), ('Duplicado de', 'Duplicado de'), ('Sigue a', 'Sigue a')], default='Relacionado con', max_length=20)),
            ],
            options={
                'verbose_name': 'Relación de Ticket',
                'verbose_name_plural': 'Relaciones de Tickets',
                'db_table': 'relacion_tickets',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'db_table': 'roles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SlaControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('tiempo_objetivo_horas', models.IntegerField(default=48)),
                ('tiempo_real_horas', models.IntegerField(blank=True, editable=False, null=True)),
                ('cumplimiento', models.BooleanField(blank=True, editable=False, null=True)),
            ],
            options={
                'verbose_name': 'Control SLA',
                'verbose_name_plural': 'Controles SLA',
                'db_table': 'sla_control',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('prioridad', models.CharField(choices=[('Baja', 'Baja'), ('Media', 'Media'), ('Alta', 'Alta'), ('Crítica', 'Crítica')], default='Media', max_length=10)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_actualizacion', models.DateField(blank=True, null=True)),
                ('fecha_cierre', models.DateField(blank=True, null=True)),
                ('duracion_dias', models.IntegerField(blank=True, editable=False, null=True)),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'db_table': 'tickets',
                'ordering': ['-fecha_inicio'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.CharField(max_length=150, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuarios',
                'managed': False,
            },
        ),
    ]
